sudo: required
dist: trusty
language: generic

install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt551-trusty
  - sudo apt-get update
  - sudo apt-get -y install pep8 pyflakes python python-pip npm nodejs nodejs-legacy
  - sudo apt-get -y install qt55declarative
  - sudo apt-get -y install qt55quickcontrols qt55graphicaleffects
  - sudo apt-get -y install qt55tools
  - sudo apt-get -y install xvfb
  - sudo npm install -g jshint

script:
  - source /opt/qt55/bin/qt55-env.sh
  - qmake .
  - make
  - make install
  - xvfb-run -a -s "-screen 0 800x600x24" make check
  - ./scripts/lint.sh

notifications:
  slack: papyros:Z7PeY2Y4mh0GWPoypZZNLd3D
